### ISSUE TITLE
Theme selection

### ISSUE THREAD

**Issue by timkrief** [johnnesky/beepbox#10]
I'm a long-time user and creator of custom-made CSS styles for personal use. I made this theme for beepbox and I'm sure other people might have created themes too, It might be funny to make them available for other users with a "use an experimental theme" option somewhere, opening a selection menu with multiple theme options.

_The theme is experimental right now because I had to use "sketchy" CSS code to make what I needed since I only have access to CSS for my styling, and because I made it to suit my needs, so it's made to be use in fullscreen mode. Plus, I'm the only one using/testing it and I used some advanced CSS properties that could not work on some machines/browsers. However, it could be made as a proper clean theme with some work._

![Capture d’écran de 2020-05-07 02-03-58](https://user-images.githubusercontent.com/14089949/81240262-31a09600-9007-11ea-929d-d8aeb6c927bb.png)
![Capture d’écran de 2020-05-07 02-26-55](https://user-images.githubusercontent.com/14089949/81241361-4a5e7b00-900a-11ea-83fd-e47ad53f282e.png)

If you don't like the concept or have other priorities, please ignore this, this is more like an enhancement idea, not something I need at all. BeepBox is my favorite audio tool yet, keep up the good work :) !

**Comment by johnnesky** [comment]
Hi! That's really cool, I'd love to learn how you did some of that stuff. Unfortunately, I don't have a lot of free time at the moment, but as it turns out JummBox already has a theme selection menu, you might try pinging Jummbus about that:
https://github.com/jummbus/jummbox

I'm impressed you made the notes rounded, does it work with pitch bends and closely placed notes? Is that using some kind of blur/threshold technique or does it actually round the corners of the svg paths somehow?

Also, I don't know if this was unintentional but it looks like you brought back BeepBox's original channel color scheme!
https://web.archive.org/web/20131008080907/http://www.beepbox.co/

**Comment by timkrief** [comment]
I didn't know about jummbox. I also didn't know about the original channel color scheme! I just used one of my favorite colors what a coincidence. But I can easily revert back to current colors.

Thanks I'm glad to hear that you like it. It does seem to work pretty well even in the edge cases you mentioned (after a lot of tweaking!). Here's a stress test:
![image](https://user-images.githubusercontent.com/14089949/81255912-3f6a1180-902f-11ea-845a-db01e83d6a62.png)
![image](https://user-images.githubusercontent.com/14089949/81256671-6e818280-9031-11ea-8962-1a957eeb4029.png)

It works thanks to a svg gooey filter (which is a blur/threshold technique indeed) used in css, and the way I used it in css is by using the svg filter as a resource passed as data uri. It's really ugly but it does the trick.
`--goo-filter: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='goo'%3E%3CfeGaussianBlur stdDeviation='5' /%3E%3CfeColorMatrix mode='matrix' values='1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 19 -9' /%3E%3C/filter%3E%3C/svg%3E#goo");`

It also kind of works when notes are closely placed: (worst case scenario here)
![image](https://user-images.githubusercontent.com/14089949/81257107-bbb22400-9032-11ea-8086-9e4292800209.png)
![image](https://user-images.githubusercontent.com/14089949/81257045-8574a480-9032-11ea-8ecd-08809e631255.png)
Because I'm also using an erode filter.

I'll check the other project, in the meantime, I might create a repo for the theme so that it can be used by others easily on BeepBox.co with something like the stylus addon.

**Comment by timkrief** [comment]
As I was saying months ago, I finally released it as a custom style on its own to be used with an add-on like stylus. It's available here: https://gitlab.com/timkrief/slick-beepbox

![image](https://user-images.githubusercontent.com/14089949/102919642-822b0d80-4489-11eb-9f16-f0aa2e866449.png)

I used the MIT license so it's compatible with beepbox and most modded beepbox, if people want to add it natively.
