### ISSUE TITLE
Copy & Paste Instrument Options are placed inconveniently

### ISSUE THREAD

**Issue by Sosasees** [johnnesky/beepbox#15]
Sometimes, the "Random Instrument" option gives me an instrument so nice, that I either want to use it multiple times or use it as the base for another instrument in the piece.

Right now in Beepbox 3.0.9, I have to manually adjust the values on the target instrument while comparing them to the goal instrument.

If there were "Copy Instrument" and "Paste Instrument" buttons in the "Edit" menu, I'd no longer have to adjust instruments manually for the purpose of making an identical instrument.

**Comment by StinkerB06** [comment]
You can copy/paste instruments already.

**Comment by Sosasees** [comment]
How? I can't find that option.
Otherwise I wouldn't have opened this issue

**Comment by StinkerB06** [comment]
It's right under "Edit" in the instrument menu.
![BeepBox Copy Paste Instrument](https://user-images.githubusercontent.com/30059831/94989862-99162f80-052c-11eb-82f4-bd435cf2b403.png)

**Comment by Sosasees** [comment]
Thanks very much!
Even though I think this placement doesn't make as much sense as in the Edit menu itself, this comment is really helpful.
I should change this issue to
"Copy & Paste Instrument Options are placed inconveniently"
