### ISSUE TITLE
Audio Popping/Cracking on Chrome-based Browsers

### ISSUE THREAD

**Issue by PQCraft** [johnnesky/beepbox#22]
I have confirmed that this is not an issue on Firefox (I have both Brave and Firefox installed) but most people use a Chrome-based browser

**Comment by johnnesky** [comment]
Yep. :/ I don't think there's much I can do about it, but it sounds like a fix is coming as soon as they can get it into a new Chrome release, see:
https://twitter.com/shaktool/status/1373353633639669762
https://bugs.chromium.org/p/chromium/issues/detail?id=1187016

**Comment by PQCraft** [comment]
@johnnesky Ah ok, i'll close this issue as this is not fixable lol, sorry for the trouble
