### ISSUE TITLE
Adding more than 4 notes on the same column

### ISSUE THREAD

**Issue by shukenmg** [johnnesky/beepbox#24]
Hello, how do I add more than 4 notes on one column?
![image](https://user-images.githubusercontent.com/18000205/114561742-6948a100-9ca0-11eb-9399-fe960c1fe8f4.png)
Adding one more note deletes the first note.

Thanks.

**Comment by johnnesky** [comment]
Hi! The most common way to make larger chords is to just use more than one channel, putting up to four notes in each channel.

Alternatively, you could try using a different version of BeepBox called CardboardBox, which allows many more simultaneous notes per channel: 
https://hidden-realm.github.io/cardboardbox

Which is actually based on another version of BeepBox called JummBox, which has a bunch of extra features but still limits the simultaneous notes per channel to 4:
https://jummbus.bitbucket.io/

**Comment by shukenmg** [comment]
> Hi! The most common way to make larger chords is to just use more than one channel, putting up to four notes in each channel.
> 
> Alternatively, you could try using a different version of BeepBox called CardboardBox, which allows many more simultaneous notes per channel:
> https://hidden-realm.github.io/cardboardbox
> 
> Which is actually based on another version of BeepBox called JummBox, which has a bunch of extra features but still limits the simultaneous notes per channel to 4:
> https://jummbus.bitbucket.io/

Perfect, thank you.

**Comment by CST1229** [comment]
> Hi! The most common way to make larger chords is to just use more than one channel, putting up to four notes in each channel.

But why is this limitation even a thing?
