### ISSUE TITLE
How do you delete EQ filter points on mobile?

### ISSUE THREAD

**Issue by StinkerB06** [johnnesky/beepbox#40]
Is it just me or is it actually impossible to remove filter points from an instrument?

On desktop, you click on a point to remove it, but on mobile, tapping to remove doesn't seem to work. Do you have to be very precise?

**Comment by johnnesky** [comment]
You can remove filter points by dragging them off the side of the filter editor.

**Comment by StinkerB06** [comment]
Oh! 🤯 Thank you!
