### ISSUE TITLE
Exporting a song with multiple drum channels to MIDI doesn't work properly

### ISSUE THREAD

**Issue by Dogo6647** [johnnesky/beepbox#49]
The first drum channel works fine, but the other ones get converted to "tink" noises. Is this a MIDI limitation or is it an actual bug from beepbox? Here's an example of an affected midi file:
[mid-full.zip](https://github.com/johnnesky/beepbox/files/9650764/mid-full.zip)

**Comment by johnnesky** [comment]
Yeah that's a MIDI limitation. MIDI allows up to 16 channels, exactly one of which can be a drum set channel.
