### ISSUE TITLE
COPYRIGHT RELATED - "Commercial" use?

### ISSUE THREAD

**Issue by MinecraftMoments** [johnnesky/beepbox#57]
I do not know where to ask this, and I do not use twitter, so I will ask this here. If this question is answered on the site, I have not been able to find it (and I'm not counting the "it's free to use" as in "you can use it to make money", although it does sloghtly imply it but i want to be absolutely certain).

The question is basically: _Can someone export a song raw from Beepbox and ask for money when resharing it?_ 

I will absolutely add credits and links to beepbox regardless if I'm able to accept money with the music from it or not, as it's a super helpful, but I also want to keep the song in the style of the Beepbox instrumentsm so I want to ask if it would be within basically the TOS of the site to ask for money for my music that's created by this project. Cannot say for certain if I will ask for money, but I want to know before I finish the soundtrack / album, just in case I do decide to put it up for purchase on bandcamp (either as a pay what you want or with a base price). I will also try to donate back to Beepbox if I get excess money (that's not going to, like, getting equipment for future music endeavors or IRL rent / food). If it's not within the TOS / if it violates copyright, I will simply use another program later to convert the song into later on, or just... Make another variation of the song available for purchase.

Thank you for reading regardless of answer, and have a good day!

**Comment by johnnesky** [comment]
Hi! To the extent that I own any license over the sounds that are synthesized by BeepBox's default instrument presets, I grant everyone a license to use them commercially. I regard BeepBox itself as being like a pen: it does not impose any restrictions over how you use it, but of course it's possible to do illegal things with it, like plagiarism. I am not a lawyer and can't help you with the intricacies of copyright law, but in general, yes, I believe you should be able to use songs you composed in BeepBox commercially.

**Comment by MinecraftMoments** [comment]
That makes sense! Thank you!
