### ISSUE TITLE
Drum channel plays broken audio on Mac

### ISSUE THREAD

**Issue by Bottle-Water** [johnnesky/beepbox#65]
All instruments routed through the drum channel have corrupt audio, making it unusable. This is present on all 4.X versions

**Comment by johnnesky** [comment]
Could you provide more information, such as an example of a song demonstrating this problem or the steps that you took to discover it? I'm on a Mac and I'm not sure how to recreate it.

**Comment by Bottle-Water** [comment]
Weird, I tried again today and can't seem to replicate the issue. I'll let you know if I can find it.
