### ISSUE TITLE
feature request: support noodling

### ISSUE THREAD

**Issue by neonpixii** [johnnesky/beepbox#67]
i would like for a mode where the keyboard/midi controller can play a synthesizer even when it's not recording, so you can try out melodies and chords without inputing them, and just generally use beepbox like a live synthesizer. this would be pretty nifty, and assuming i can ever get my midi keyboard to actually work on linux (which is a bold assumption) beep box would turn into such a useful thing to just open up whenever i need to noodle around with a piano

**Comment by johnnesky** [comment]
You already can! If you do have working MIDI input, that's one way to play sounds without recording them. You can also toggle caps-lock to use your computer keyboard to play sounds without recording, see the "Set Up Note Recording..." preference option to configure the keyboard. And technically you can click on the on-screen piano keys but that's a lot harder to use.
