### ISSUE TITLE
request: phase control

### ISSUE THREAD

**Issue by M0ahgra** [johnnesky/beepbox#68]
could there be an option to directly control the phase of a waveform? it is small, but i personally have used phase shifts to create interesting patterns.

an example beepbox song: https://tinyurl.com/ypjb9vp3

this was done by swinging the pitch at the start one the instruments, swinging the pitch causes a phase shift, and the (continue) setting causes the instrument to keep this phase shift forever, it would be cool to be able to do this directly!

**Comment by johnnesky** [comment]
It probably wouldn't be clear to a beginner what would be the point of any phase controls, and a major goal of BeepBox's design is to not overwhelm users with confusing options, providing the minimum number of options necessary to be able to be creative. As such I don't think I'll be adding phase controls, although you might try asking the JummBox or UltraBox devs. 

https://github.com/jummbus/jummbox
https://github.com/ultraabox/ultrabox_typescript
