### ISSUE TITLE
Using >64 patterns per channel breaks BeepBox

### ISSUE THREAD

**Issue by StinkerB06** [johnnesky/beepbox#7]
The newest update (3.0.2) appears to have doubled the "Patterns per channel" limit from 64 to 128. However, when trying to use more than 64 patterns, BeepBox crashes.

Side note: My infamous [BruceBox](https://github.com/StinkerB06/BruceBox) mod from two years ago (which was based on a very-old build of Modded BeepBox) has had a similar bug when I decided to double the limit.

**Comment by johnnesky** [comment]
Aha! Good catch, I'll try to address that today, thanks.

**Comment by StinkerB06** [comment]
I just saw that you released a patch for BeepBox 3.0.2 in the releases section. I've refreshed the page several times, but I didn't notice the URL change from `7` to `8` yet.

**Comment by StinkerB06** [comment]
Alright, it's out now. Closing...
