### ISSUE TITLE
Edit box value exceeding

### ISSUE THREAD

**Issue by Nathan-R-Og** [johnnesky/beepbox#9]
I noticed on the twitter feed on the site that you asked about someone exceeding the limits of channels. Well, I found out _how_, but I honestly think it's a neat little bug. For example, if you go to channel settings and set a value to way past its max, eg the number of drum channels to 17, and only press enter without leaving the edit box, you can apply it without the max/min getting applied. Same goes for song length and beats per measure. If it could be a toggle or some kind of "extra expert" feature, I bet that would be really cool, as to not distract from the sole purpose of the program and be simple, but also be very flexible.

Dunno if that helps or not.

(also note, this works on a lot of other beepbox branches, like jummbox. 2 other things, on jummbox you can use this to export as midi when it sometimes doesn't work, and oddly modbox is not affected by this. just thought i'd throw these in here too.)

**Comment by johnnesky** [comment]
Oh, excellent, thank you for the bug report! Dunno how I missed that before, but I can replicate it now with your instructions! I will fix it soon, because it is causing confusing bugs for people. I am deliberately limiting these numbers, but feel free to use the higher limits on jummbox/etc.

**Comment by Nathan-R-Og** [comment]
Thanks, will do
